# Generated by Django 4.2 on 2023-05-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='type',
            field=models.TextField(choices=[('Al', 'Alimentaire'), ('Mb', 'Meuble'), ('Sn', 'Sanitaire'), ('Vs', 'Vaisselle'), ('Vt', 'Vêtement'), ('Jx', 'Jouets'), ('Lg', 'Linge de Maison'), ('Bj', 'Bijoux'), ('Dc', 'Décor'), ('Im', 'Immobilier'), ('Me', 'Meuble'), ('Pp', 'ParaPharmacie'), ('El', 'Electroménager'), ('Fr', 'Frais'), ('Ta', 'Tapis'), ('CI', 'Composant Informatique')], default='Ai', max_length=50),
        ),
    ]
